[package]
name = "football_heaven"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
and = "0.8"          # For random number generation
serde_json = "1.0"    # For JSON serialization
indicatif = "0.16"    # For progress bar