"""
Centralized csv_reader module.

Going forward, prefer importing from `const` instead of `csv_reader`.
`csv_reader.py` is kept for compatibility and still contains the large constant maps.
"""

END_YEAR = 2025
LEAGUES = ["NFL", "NCAA"]
VERSIONS = ["0.0", "0.1", "1.0", "1.1", "2.0", "2.1", "3.0", "3.1", "4.0"]
NCAA_WEEKS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
NFL_WEEKS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 28, 29, 30, 32]
NFL_LINK = "https://premium.pff.com/{league}/positions/{year}/SINGLE/{stat_type}?week={week}"
NCAA_LINK = "https://premium.pff.com/{league}/positions/{year}/SINGLE/{stat_type}?division=fbs,fcs,lower&week={week}"

LEAGUE_YEARS = {
    "NFL": {
        "start_year": 2006,
        "end_year": END_YEAR
    },
    "NCAA": {
        "start_year": 2014,
        "end_year": END_YEAR
    }
}

STAT_TYPES = [
    "passing",
    "passing-depth",
    "passing-pressure",
    "passing-concept",
    "receiving",
    "receiving-depth",
    "receiving-scheme",
    "rushing",
    "offense-blocking",
    "offense-pass-blocking",
    "offense-run-blocking",
    "defense-pass-rush",
    "defense-run",
    "defense-coverage",
    "defense-coverage-scheme"

]

TEAM_ABR_TO_FULL = {
    "ARZ": "Arizona Cardinals",
    "ATL": "Atlanta Falcons",
    "BLT": "Baltimore Ravens",
    "BUF": "Buffalo Bills",
    "CAR": "Carolina Panthers",
    "CHI": "Chicago Bears",
    "CIN": "Cincinnati Bengals",
    "CLV": "Cleveland Browns",
    "DAL": "Dallas Cowboys",
    "DEN": "Denver Broncos",
    "DET": "Detroit Lions",
    "GB": "Green Bay Packers",
    "HST": "Houston Texans",
    "IND": "Indianapolis Colts",
    "JAX": "Jacksonville Jaguars",
    "KC": "Kansas City Chiefs",
    "LA": "Los Angeles Rams",
    "LAC": "Los Angeles Chargers",
    "LV": "Las Vegas Raiders",
    "MIA": "Miami Dolphins",
    "MIN": "Minnesota Vikings",
    "NE": "New England Patriots",
    "NO": "New Orleans Saints",
    "NYG": "New York Giants",
    "NYJ": "New York Jets",
    "OAK": "Oakland Raiders",
    "PHI": "Philadelphia Eagles",
    "PIT": "Pittsburgh Steelers",
    "SF": "San Francisco 49ers",
    "SEA": "Seattle Seawhawks",
    "SD": "San Diego Chargers",
    "SL": "St. Louis Rams",
    "TB": "Tampa Bay Buccaneers",
    "TEN": "Tennessee Titans",
    "WAS": "Washington Redskins"
}

PLAYOFF_WEEK_CODE_START = 29
PLAYOFF_WEEK_CODE_END = 32
PLAYOFF_WEEK_NORMALIZED_START = 19

# PFF uses weeks 28-30, 32 for playoffs; games CSV uses 29-31, 32.
# PFF weeks 28-30 need +1 adjustment before normalization.
PFF_PLAYOFF_WEEK_OFFSET_START = 28
PFF_PLAYOFF_WEEK_OFFSET_END = 30


def normalize_week(week: int, *, is_pff_data: bool = True) -> int:
    """Normalize week numbering to a single, human-friendly scheme.

    - Regular season weeks remain unchanged (1-18).
    - Playoff week codes 29-32 are remapped to 19-22.

    Args:
        week: The week number from the source data.
        is_pff_data: If True (default), applies PFF-specific adjustment for
            weeks 28-30 (adds +1 to align with games CSV numbering).
    """
    # PFF player stats use weeks 28-30 for playoffs (no week 31),
    # while games CSV uses 29-31 for the same rounds. Adjust PFF weeks.
    if is_pff_data and PFF_PLAYOFF_WEEK_OFFSET_START <= week <= PFF_PLAYOFF_WEEK_OFFSET_END:
        week += 1

    if week >= PLAYOFF_WEEK_CODE_START:
        return PLAYOFF_WEEK_NORMALIZED_START + (week - PLAYOFF_WEEK_CODE_START)
    return week


PASSING = [
    "aimed_passes",
    "attempts",
    "avg_depth_of_target",
    "bats",
    "big_time_throws",
    "completions",
    "dropbacks",
    "drops",
    "first_downs",
    "hit_as_threw",
    "interceptions",
    "passing_snaps",
    "penalties",
    "sacks",
    "scrambles",
    "spikes",
    "thrown_aways",
    "touchdowns",
    "turnover_worthy_plays",
    "yards",
    "grades_pass",
]



PASSING_DEPTH = [
    "center_behind_los_aimed_passes",
    "center_behind_los_attempts",
    "center_behind_los_avg_depth_of_target",
    "center_behind_los_bats",
    "center_behind_los_big_time_throws",
    "center_behind_los_completions",
    "center_behind_los_dropbacks",
    "center_behind_los_drops",
    "center_behind_los_first_downs",
    "center_behind_los_grades_pass",
    "center_behind_los_hit_as_threw",
    "center_behind_los_interceptions",
    "center_behind_los_passing_snaps",
    "center_behind_los_penalties",
    "center_behind_los_sacks",
    "center_behind_los_scrambles",
    "center_behind_los_spikes",
    "center_behind_los_thrown_aways",
    "center_behind_los_touchdowns",
    "center_behind_los_turnover_worthy_plays",
    "center_behind_los_yards",
    "center_deep_aimed_passes",
    "center_deep_attempts",
    "center_deep_avg_depth_of_target",
    "center_deep_bats",
    "center_deep_big_time_throws",
    "center_deep_completions",
    "center_deep_dropbacks",
    "center_deep_drops",
    "center_deep_first_downs",
    "center_deep_grades_pass",
    "center_deep_hit_as_threw",
    "center_deep_interceptions",
    "center_deep_passing_snaps",
    "center_deep_penalties",
    "center_deep_sacks",
    "center_deep_scrambles",
    "center_deep_spikes",
    "center_deep_thrown_aways",
    "center_deep_touchdowns",
    "center_deep_turnover_worthy_plays",
    "center_deep_yards",
    "center_medium_aimed_passes",
    "center_medium_attempts",
    "center_medium_avg_depth_of_target",
    "center_medium_bats",
    "center_medium_big_time_throws",
    "center_medium_completions",
    "center_medium_dropbacks",
    "center_medium_drops",
    "center_medium_first_downs",
    "center_medium_grades_pass",
    "center_medium_hit_as_threw",
    "center_medium_interceptions",
    "center_medium_passing_snaps",
    "center_medium_penalties",
    "center_medium_sacks",
    "center_medium_scrambles",
    "center_medium_spikes",
    "center_medium_thrown_aways",
    "center_medium_touchdowns",
    "center_medium_turnover_worthy_plays",
    "center_medium_yards",
    "center_short_aimed_passes",
    "center_short_attempts",
    "center_short_avg_depth_of_target",
    "center_short_bats",
    "center_short_big_time_throws",
    "center_short_completions",
    "center_short_dropbacks",
    "center_short_drops",
    "center_short_first_downs",
    "center_short_grades_pass",
    "center_short_hit_as_threw",
    "center_short_interceptions",
    "center_short_passing_snaps",
    "center_short_penalties",
    "center_short_sacks",
    "center_short_scrambles",
    "center_short_spikes",
    "center_short_thrown_aways",
    "center_short_touchdowns",
    "center_short_turnover_worthy_plays",
    "center_short_yards",
    "left_behind_los_aimed_passes",
    "left_behind_los_attempts",
    "left_behind_los_avg_depth_of_target",
    "left_behind_los_bats",
    "left_behind_los_big_time_throws",
    "left_behind_los_completions",
    "left_behind_los_dropbacks",
    "left_behind_los_drops",
    "left_behind_los_first_downs",
    "left_behind_los_grades_pass",
    "left_behind_los_hit_as_threw",
    "left_behind_los_interceptions",
    "left_behind_los_passing_snaps",
    "left_behind_los_penalties",
    "left_behind_los_sacks",
    "left_behind_los_scrambles",
    "left_behind_los_spikes",
    "left_behind_los_thrown_aways",
    "left_behind_los_touchdowns",
    "left_behind_los_turnover_worthy_plays",
    "left_behind_los_yards",
    "left_deep_aimed_passes",
    "left_deep_attempts",
    "left_deep_avg_depth_of_target",
    "left_deep_bats",
    "left_deep_big_time_throws",
    "left_deep_completions",
    "left_deep_dropbacks",
    "left_deep_drops",
    "left_deep_first_downs",
    "left_deep_grades_pass",
    "left_deep_hit_as_threw",
    "left_deep_interceptions",
    "left_deep_passing_snaps",
    "left_deep_penalties",
    "left_deep_sacks",
    "left_deep_scrambles",
    "left_deep_spikes",
    "left_deep_thrown_aways",
    "left_deep_touchdowns",
    "left_deep_turnover_worthy_plays",
    "left_deep_yards",
    "left_medium_aimed_passes",
    "left_medium_attempts",
    "left_medium_avg_depth_of_target",
    "left_medium_bats",
    "left_medium_big_time_throws",
    "left_medium_completions",
    "left_medium_dropbacks",
    "left_medium_drops",
    "left_medium_first_downs",
    "left_medium_grades_pass",
    "left_medium_hit_as_threw",
    "left_medium_interceptions",
    "left_medium_passing_snaps",
    "left_medium_penalties",
    "left_medium_sacks",
    "left_medium_scrambles",
    "left_medium_spikes",
    "left_medium_thrown_aways",
    "left_medium_touchdowns",
    "left_medium_turnover_worthy_plays",
    "left_medium_yards",
    "left_short_aimed_passes",
    "left_short_attempts",
    "left_short_avg_depth_of_target",
    "left_short_bats",
    "left_short_big_time_throws",
    "left_short_completions",
    "left_short_dropbacks",
    "left_short_drops",
    "left_short_first_downs",
    "left_short_grades_pass",
    "left_short_hit_as_threw",
    "left_short_interceptions",
    "left_short_passing_snaps",
    "left_short_penalties",
    "left_short_sacks",
    "left_short_scrambles",
    "left_short_spikes",
    "left_short_thrown_aways",
    "left_short_touchdowns",
    "left_short_turnover_worthy_plays",
    "left_short_yards",
    "right_behind_los_aimed_passes",
    "right_behind_los_attempts",
    "right_behind_los_avg_depth_of_target",
    "right_behind_los_bats",
    "right_behind_los_big_time_throws",
    "right_behind_los_completions",
    "right_behind_los_dropbacks",
    "right_behind_los_drops",
    "right_behind_los_first_downs",
    "right_behind_los_grades_pass",
    "right_behind_los_hit_as_threw",
    "right_behind_los_interceptions",
    "right_behind_los_passing_snaps",
    "right_behind_los_penalties",
    "right_behind_los_sacks",
    "right_behind_los_scrambles",
    "right_behind_los_spikes",
    "right_behind_los_thrown_aways",
    "right_behind_los_touchdowns",
    "right_behind_los_turnover_worthy_plays",
    "right_behind_los_yards",
    "right_deep_aimed_passes",
    "right_deep_attempts",
    "right_deep_avg_depth_of_target",
    "right_deep_bats",
    "right_deep_big_time_throws",
    "right_deep_completions",
    "right_deep_dropbacks",
    "right_deep_drops",
    "right_deep_first_downs",
    "right_deep_grades_pass",
    "right_deep_hit_as_threw",
    "right_deep_interceptions",
    "right_deep_passing_snaps",
    "right_deep_penalties",
    "right_deep_sacks",
    "right_deep_scrambles",
    "right_deep_spikes",
    "right_deep_thrown_aways",
    "right_deep_touchdowns",
    "right_deep_turnover_worthy_plays",
    "right_deep_yards",
    "right_medium_aimed_passes",
    "right_medium_attempts",
    "right_medium_avg_depth_of_target",
    "right_medium_bats",
    "right_medium_big_time_throws",
    "right_medium_completions",
    "right_medium_dropbacks",
    "right_medium_drops",
    "right_medium_first_downs",
    "right_medium_grades_pass",
    "right_medium_hit_as_threw",
    "right_medium_interceptions",
    "right_medium_passing_snaps",
    "right_medium_penalties",
    "right_medium_sacks",
    "right_medium_scrambles",
    "right_medium_spikes",
    "right_medium_thrown_aways",
    "right_medium_touchdowns",
    "right_medium_turnover_worthy_plays",
    "right_medium_yards",
    "right_short_aimed_passes",
    "right_short_attempts",
    "right_short_avg_depth_of_target",
    "right_short_bats",
    "right_short_big_time_throws",
    "right_short_completions",
    "right_short_dropbacks",
    "right_short_drops",
    "right_short_first_downs",
    "right_short_grades_pass",
    "right_short_hit_as_threw",
    "right_short_interceptions",
    "right_short_passing_snaps",
    "right_short_penalties",
    "right_short_sacks",
    "right_short_scrambles",
    "right_short_spikes",
    "right_short_thrown_aways",
    "right_short_touchdowns",
    "right_short_turnover_worthy_plays",
    "right_short_yards",
]



PASSING_PRESSURE = [
    "blitz_aimed_passes",
    "blitz_attempts",
    "blitz_avg_depth_of_target",
    "blitz_bats",
    "blitz_big_time_throws",
    "blitz_completions",
    "blitz_dropbacks",
    "blitz_drops",
    "blitz_first_downs",
    "blitz_grades_pass",
    "blitz_hit_as_threw",
    "blitz_interceptions",
    "blitz_passing_snaps",
    "blitz_penalties",
    "blitz_sacks",
    "blitz_scrambles",
    "blitz_spikes",
    "blitz_thrown_aways",
    "blitz_touchdowns",
    "blitz_turnover_worthy_plays",
    "blitz_yards",
    "no_blitz_aimed_passes",
    "no_blitz_attempts",
    "no_blitz_avg_depth_of_target",
    "no_blitz_bats",
    "no_blitz_big_time_throws",
    "no_blitz_completions",
    "no_blitz_dropbacks",
    "no_blitz_drops",
    "no_blitz_first_downs",
    "no_blitz_grades_pass",
    "no_blitz_hit_as_threw",
    "no_blitz_interceptions",
    "no_blitz_passing_snaps",
    "no_blitz_penalties",
    "no_blitz_sacks",
    "no_blitz_scrambles",
    "no_blitz_spikes",
    "no_blitz_thrown_aways",
    "no_blitz_touchdowns",
    "no_blitz_turnover_worthy_plays",
    "no_blitz_yards",
    "no_pressure_aimed_passes",
    "no_pressure_attempts",
    "no_pressure_avg_depth_of_target",
    "no_pressure_bats",
    "no_pressure_big_time_throws",
    "no_pressure_completions",
    "no_pressure_dropbacks",
    "no_pressure_drops",
    "no_pressure_first_downs",
    "no_pressure_grades_pass",
    "no_pressure_hit_as_threw",
    "no_pressure_interceptions",
    "no_pressure_passing_snaps",
    "no_pressure_penalties",
    "no_pressure_sacks",
    "no_pressure_scrambles",
    "no_pressure_spikes",
    "no_pressure_thrown_aways",
    "no_pressure_touchdowns",
    "no_pressure_turnover_worthy_plays",
    "no_pressure_yards",
    "pressure_aimed_passes",
    "pressure_attempts",
    "pressure_avg_depth_of_target",
    "pressure_bats",
    "pressure_big_time_throws",
    "pressure_completions",
    "pressure_dropbacks",
    "pressure_drops",
    "pressure_first_downs",
    "pressure_grades_pass",
    "pressure_hit_as_threw",
    "pressure_interceptions",
    "pressure_passing_snaps",
    "pressure_penalties",
    "pressure_sacks",
    "pressure_scrambles",
    "pressure_spikes",
    "pressure_thrown_aways",
    "pressure_touchdowns",
    "pressure_turnover_worthy_plays",
    "pressure_yards",
]



RECEIVING_ = [
    "avoided_tackles",
    "contested_receptions",
    "contested_targets",
    "drops",
    "first_downs",
    "fumbles",
    "inline_snaps",
    "interceptions",
    "penalties",
    "receptions",
    "routes",
    "slot_snaps",
    "targets",
    "touchdowns",
    "wide_snaps",
    "yards",
    "yards_after_catch",
    "grades_hands_drop",
    "grades_pass_route",
]



RECEIVING_DEPTH = [
    "center_behind_los_avoided_tackles",
    "center_behind_los_contested_receptions",
    "center_behind_los_contested_targets",
    "center_behind_los_drops",
    "center_behind_los_first_downs",
    "center_behind_los_fumbles",
    "center_behind_los_grades_hands_drop",
    "center_behind_los_grades_pass_route",
    "center_behind_los_inline_snaps",
    "center_behind_los_interceptions",
    "center_behind_los_penalties",
    "center_behind_los_receptions",
    "center_behind_los_routes",
    "center_behind_los_slot_snaps",
    "center_behind_los_targets",
    "center_behind_los_touchdowns",
    "center_behind_los_wide_snaps",
    "center_behind_los_yards",
    "center_behind_los_yards_after_catch",
    "center_deep_avoided_tackles",
    "center_deep_contested_receptions",
    "center_deep_contested_targets",
    "center_deep_drops",
    "center_deep_first_downs",
    "center_deep_fumbles",
    "center_deep_grades_hands_drop",
    "center_deep_grades_pass_route",
    "center_deep_inline_snaps",
    "center_deep_interceptions",
    "center_deep_penalties",
    "center_deep_receptions",
    "center_deep_routes",
    "center_deep_slot_snaps",
    "center_deep_targets",
    "center_deep_touchdowns",
    "center_deep_wide_snaps",
    "center_deep_yards",
    "center_deep_yards_after_catch",
    "center_medium_avoided_tackles",
    "center_medium_contested_receptions",
    "center_medium_contested_targets",
    "center_medium_drops",
    "center_medium_first_downs",
    "center_medium_fumbles",
    "center_medium_grades_hands_drop",
    "center_medium_grades_pass_route",
    "center_medium_inline_snaps",
    "center_medium_interceptions",
    "center_medium_penalties",
    "center_medium_receptions",
    "center_medium_routes",
    "center_medium_slot_snaps",
    "center_medium_targets",
    "center_medium_touchdowns",
    "center_medium_wide_snaps",
    "center_medium_yards",
    "center_medium_yards_after_catch",
    "center_short_avoided_tackles",
    "center_short_contested_receptions",
    "center_short_contested_targets",
    "center_short_drops",
    "center_short_first_downs",
    "center_short_fumbles",
    "center_short_grades_hands_drop",
    "center_short_grades_pass_route",
    "center_short_inline_snaps",
    "center_short_interceptions",
    "center_short_penalties",
    "center_short_receptions",
    "center_short_routes",
    "center_short_slot_snaps",
    "center_short_targets",
    "center_short_touchdowns",
    "center_short_wide_snaps",
    "center_short_yards",
    "center_short_yards_after_catch",
    "left_behind_los_avoided_tackles",
    "left_behind_los_contested_receptions",
    "left_behind_los_contested_targets",
    "left_behind_los_drops",
    "left_behind_los_first_downs",
    "left_behind_los_fumbles",
    "left_behind_los_grades_hands_drop",
    "left_behind_los_grades_pass_route",
    "left_behind_los_inline_snaps",
    "left_behind_los_interceptions",
    "left_behind_los_penalties",
    "left_behind_los_receptions",
    "left_behind_los_routes",
    "left_behind_los_slot_snaps",
    "left_behind_los_targets",
    "left_behind_los_touchdowns",
    "left_behind_los_wide_snaps",
    "left_behind_los_yards",
    "left_behind_los_yards_after_catch",
    "left_deep_avoided_tackles",
    "left_deep_contested_receptions",
    "left_deep_contested_targets",
    "left_deep_drops",
    "left_deep_first_downs",
    "left_deep_fumbles",
    "left_deep_grades_hands_drop",
    "left_deep_grades_pass_route",
    "left_deep_inline_snaps",
    "left_deep_interceptions",
    "left_deep_penalties",
    "left_deep_receptions",
    "left_deep_routes",
    "left_deep_slot_snaps",
    "left_deep_targets",
    "left_deep_touchdowns",
    "left_deep_wide_snaps",
    "left_deep_yards",
    "left_deep_yards_after_catch",
    "left_medium_avoided_tackles",
    "left_medium_contested_receptions",
    "left_medium_contested_targets",
    "left_medium_drops",
    "left_medium_first_downs",
    "left_medium_fumbles",
    "left_medium_grades_hands_drop",
    "left_medium_grades_pass_route",
    "left_medium_inline_snaps",
    "left_medium_interceptions",
    "left_medium_penalties",
    "left_medium_receptions",
    "left_medium_routes",
    "left_medium_slot_snaps",
    "left_medium_targets",
    "left_medium_touchdowns",
    "left_medium_wide_snaps",
    "left_medium_yards",
    "left_medium_yards_after_catch",
    "left_short_avoided_tackles",
    "left_short_contested_receptions",
    "left_short_contested_targets",
    "left_short_drops",
    "left_short_first_downs",
    "left_short_fumbles",
    "left_short_grades_hands_drop",
    "left_short_grades_pass_route",
    "left_short_inline_snaps",
    "left_short_interceptions",
    "left_short_penalties",
    "left_short_receptions",
    "left_short_routes",
    "left_short_slot_snaps",
    "left_short_targets",
    "left_short_touchdowns",
    "left_short_wide_snaps",
    "left_short_yards",
    "left_short_yards_after_catch",
    "right_behind_los_avoided_tackles",
    "right_behind_los_contested_receptions",
    "right_behind_los_contested_targets",
    "right_behind_los_drops",
    "right_behind_los_first_downs",
    "right_behind_los_fumbles",
    "right_behind_los_grades_hands_drop",
    "right_behind_los_grades_pass_route",
    "right_behind_los_inline_snaps",
    "right_behind_los_interceptions",
    "right_behind_los_penalties",
    "right_behind_los_receptions",
    "right_behind_los_routes",
    "right_behind_los_slot_snaps",
    "right_behind_los_targets",
    "right_behind_los_touchdowns",
    "right_behind_los_wide_snaps",
    "right_behind_los_yards",
    "right_behind_los_yards_after_catch",
    "right_deep_avoided_tackles",
    "right_deep_contested_receptions",
    "right_deep_contested_targets",
    "right_deep_drops",
    "right_deep_first_downs",
    "right_deep_fumbles",
    "right_deep_grades_hands_drop",
    "right_deep_grades_pass_route",
    "right_deep_inline_snaps",
    "right_deep_interceptions",
    "right_deep_penalties",
    "right_deep_receptions",
    "right_deep_routes",
    "right_deep_slot_snaps",
    "right_deep_targets",
    "right_deep_touchdowns",
    "right_deep_wide_snaps",
    "right_deep_yards",
    "right_deep_yards_after_catch",
    "right_medium_avoided_tackles",
    "right_medium_contested_receptions",
    "right_medium_contested_targets",
    "right_medium_drops",
    "right_medium_first_downs",
    "right_medium_fumbles",
    "right_medium_grades_hands_drop",
    "right_medium_grades_pass_route",
    "right_medium_inline_snaps",
    "right_medium_interceptions",
    "right_medium_penalties",
    "right_medium_receptions",
    "right_medium_routes",
    "right_medium_slot_snaps",
    "right_medium_targets",
    "right_medium_touchdowns",
    "right_medium_wide_snaps",
    "right_medium_yards",
    "right_medium_yards_after_catch",
    "right_short_avoided_tackles",
    "right_short_contested_receptions",
    "right_short_contested_targets",
    "right_short_drops",
    "right_short_first_downs",
    "right_short_fumbles",
    "right_short_grades_hands_drop",
    "right_short_grades_pass_route",
    "right_short_inline_snaps",
    "right_short_interceptions",
    "right_short_penalties",
    "right_short_receptions",
    "right_short_routes",
    "right_short_slot_snaps",
    "right_short_targets",
    "right_short_touchdowns",
    "right_short_wide_snaps",
    "right_short_yards",
    "right_short_yards_after_catch",
]



RECEIVING_SCHEME = [
    "man_avoided_tackles",
    "man_contested_receptions",
    "man_contested_targets",
    "man_drops",
    "man_first_downs",
    "man_fumbles",
    "man_grades_hands_drop",
    "man_grades_pass_route",
    "man_inline_snaps",
    "man_interceptions",
    "man_penalties",
    "man_receptions",
    "man_routes",
    "man_slot_snaps",
    "man_targets",
    "man_touchdowns",
    "man_wide_snaps",
    "man_yards",
    "man_yards_after_catch",
    "zone_avoided_tackles",
    "zone_contested_receptions",
    "zone_contested_targets",
    "zone_drops",
    "zone_first_downs",
    "zone_fumbles",
    "zone_grades_hands_drop",
    "zone_grades_pass_route",
    "zone_inline_snaps",
    "zone_interceptions",
    "zone_penalties",
    "zone_receptions",
    "zone_routes",
    "zone_slot_snaps",
    "zone_targets",
    "zone_touchdowns",
    "zone_wide_snaps",
    "zone_yards",
    "zone_yards_after_catch",
]



RUSHING = [
    "attempts",
    "avoided_tackles",
    "breakaway_attempts",
    "breakaway_yards",
    "designed_yards",
    "explosive",
    "first_downs",
    "fumbles",
    "gap_attempts",
    "penalties",
    "run_plays",
    "scramble_yards",
    "scrambles",
    "touchdowns",
    "yards",
    "yards_after_contact",
    "zone_attempts",
    "grades_run",
    "grades_hands_fumble",
]


BLOCKING = [
    "grades_pass_block",
    "grades_run_block",
    "penalties",
    "snap_counts_ce",
    "snap_counts_lg",
    "snap_counts_lt",
    "snap_counts_offense",
    "snap_counts_pass_block",
    "snap_counts_pass_play",
    "snap_counts_rg",
    "snap_counts_rt",
    "snap_counts_run_block",
    "snap_counts_te",
]



PASS_BLOCKING = [
    "grades_pass_block",
    "hits_allowed",
    "hurries_allowed",
    "pressures_allowed",
    "sacks_allowed",
    "snap_counts_pass_play",
    "true_pass_set_grades_pass_block",
    "true_pass_set_hits_allowed",
    "true_pass_set_hurries_allowed",
    "true_pass_set_pressures_allowed",
    "true_pass_set_sacks_allowed",
    "true_pass_set_snap_counts_pass_play",
]



RUN_BLOCKING = [
    "gap_grades_run_block",
    "gap_snap_counts_run_block",
    "grades_run_block",
    "snap_counts_run_block",
    "penalties",
    "zone_grades_run_block",
    "zone_snap_counts_run_block",
]



PASS_RUSH = [
    "batted_passes",
    "grades_pass_rush_defense",
    "hits",
    "hurries",
    "pass_rush_opp",
    "pass_rush_wins",
    "penalties",
    "sacks",
    "snap_counts_pass_play",
    "snap_counts_pass_rush",
    "total_pressures",
    "true_pass_set_batted_passes",
    "true_pass_set_grades_pass_rush_defense",
    "true_pass_set_hits",
    "true_pass_set_hurries",
    "true_pass_set_pass_rush_opp",
    "true_pass_set_pass_rush_wins",
    "true_pass_set_sacks",
    "true_pass_set_snap_counts_pass_play",
    "true_pass_set_snap_counts_pass_rush",
    "true_pass_set_total_pressures",
]



RUN_DEFENSE = [
    "assists",
    "avg_depth_of_tackle",
    "forced_fumbles",
    "grades_run_defense",
    "grades_tackle",
    "missed_tackles",
    "penalties",
    "run_stop_opp",
    "stops",
    "tackles",
]



COVERAGE = [
    "avg_depth_of_target",
    "dropped_ints",
    "forced_incompletes",
    "grades_coverage_defense",
    "interceptions",
    "pass_break_ups",
    "receptions",
    "snap_counts_coverage",
    "targets",
    "touchdowns",
    "yards",
    "yards_after_catch",
]



COVERAGE_SCHEME = [
    "man_avg_depth_of_target",
    "man_dropped_ints",
    "man_forced_incompletes",
    "man_grades_coverage_defense",
    "man_interceptions",
    "man_pass_break_ups",
    "man_receptions",
    "man_snap_counts_coverage",
    "man_targets",
    "man_touchdowns",
    "man_yards",
    "man_yards_after_catch",
    "zone_avg_depth_of_target",
    "zone_dropped_ints",
    "zone_forced_incompletes",
    "zone_grades_coverage_defense",
    "zone_interceptions",
    "zone_pass_break_ups",
    "zone_receptions",
    "zone_snap_counts_coverage",
    "zone_targets",
    "zone_touchdowns",
    "zone_yards",
    "zone_yards_after_catch",
]
