PASSING = {
    "aimed_passes": 7, 
    "attempts": 8,
    "avg_depth_of_target": 9, 
    "bats": 11, 
    "big_time_throws": 12, 
    "completions": 15, 
    "dropbacks": 19, 
    "drops": 20, 
    "first_downs": 21,
    "hit_as_threw": 27, 
    "interceptions": 28, 
    "passing_snaps": 29, 
    "penalties": 30, 
    "sacks": 34, 
    "scrambles": 35, 
    "spikes": 36, 
    "thrown_aways": 37, 
    "touchdowns": 38, 
    "turnover_worthy_plays": 39, 
    "yards": 41,
    "grade_pass": 25
}



PASSING_DEPTH = {
    "BEHIND_LOS": {
        "CENTRAL": {
            "center_behind_los_aimed_passes": 41,
            "center_behind_los_attempts": 42,
            "center_behind_los_avg_depth_of_target": 44,
            "center_behind_los_bats": 46,
            "center_behind_los_big_time_throws": 47,
            "center_behind_los_completions": 50,
            "center_behind_los_dropbacks": 53,
            "center_behind_los_drops": 54,
            "center_behind_los_first_downs": 55,
            "center_behind_los_hit_as_threw": 57,
            "center_behind_los_interceptions": 58,
            "center_behind_los_passing_snaps": 59,
            "center_behind_los_penalties": None,
            "center_behind_los_sacks": 63,
            "center_behind_los_scrambles": 64,
            "center_behind_los_spikes": 65,
            "center_behind_los_thrown_aways": 66,
            "center_behind_los_touchdowns": 67,
            "center_behind_los_turnover_worthy_plays": 68,
            "center_behind_los_yards": 70,
            "center_behind_los_grade_pass": 56
        },
        "LEFT": {
            "left_behind_los_aimed_passes": 203,
            "left_behind_los_attempts": 204,
            "left_behind_los_avg_depth_of_target": 206,
            "left_behind_los_bats": 208,
            "left_behind_los_big_time_throws": 209,
            "left_behind_los_completions": 212,
            "left_behind_los_dropbacks": 215,
            "left_behind_los_drops": 216,
            "left_behind_los_first_downs": 217,
            "left_behind_los_hit_as_threw": 219,
            "left_behind_los_interceptions": 220,
            "left_behind_los_passing_snaps": 221,
            "left_behind_los_penalties": None,
            "left_behind_los_sacks": 225,
            "left_behind_los_scrambles": 226,
            "left_behind_los_spikes": 227,
            "left_behind_los_thrown_aways": 228,
            "left_behind_los_touchdowns": 229,
            "left_behind_los_turnover_worthy_plays": 230,
            "left_behind_los_yards": 232,
            "left_behind_los_grade_pass": 218
        },
        "RIGHT": {
            "right_behind_los_aimed_passes": 364,
            "right_behind_los_attempts": 365,
            "right_behind_los_avg_depth_of_target": 367,
            "right_behind_los_bats": 369,
            "right_behind_los_big_time_throws": 370,
            "right_behind_los_completions": 373,
            "right_behind_los_dropbacks": 376,
            "right_behind_los_drops": 377,
            "right_behind_los_first_downs": 378,
            "right_behind_los_hit_as_threw": 380,
            "right_behind_los_interceptions": 381,
            "right_behind_los_passing_snaps": 382,
            "right_behind_los_penalties": None,
            "right_behind_los_sacks": 386,
            "right_behind_los_scrambles": 387,
            "right_behind_los_spikes": 388,
            "right_behind_los_thrown_aways": 389,
            "right_behind_los_touchdowns": 390,
            "right_behind_los_turnover_worthy_plays": 391,
            "right_behind_los_yards": 393,
            "right_behind_los_grade_pass": 379
        }
    },
    "DEEP": {
        "CENTRAL": {
            "center_deep_aimed_passes": 73,
            "center_deep_attempts": 74,
            "center_deep_avg_depth_of_target": 76,
            "center_deep_bats": 78,
            "center_deep_big_time_throws": 79,
            "center_deep_completions": 82,
            "center_deep_dropbacks": 85,
            "center_deep_drops": 86,
            "center_deep_first_downs": 87,
            "center_deep_hit_as_threw": 89,
            "center_deep_interceptions": 90,
            "center_deep_passing_snaps": 91,
            "center_deep_penalties": None,
            "center_deep_sacks": 95,
            "center_deep_scrambles": 96,
            "center_deep_spikes": 97,
            "center_deep_thrown_aways": 98,
            "center_deep_touchdowns": 99,
            "center_deep_turnover_worthy_plays": 100,
            "center_deep_yards": 102,
            "center_deep_grade_pass": 88
        },
        "LEFT": {
            "left_deep_aimed_passes": 235,
            "left_deep_attempts": 236,
            "left_deep_avg_depth_of_target": 238,
            "left_deep_bats": 240,
            "left_deep_big_time_throws": 241,
            "left_deep_completions": 244,
            "left_deep_dropbacks": 247,
            "left_deep_drops": 248,
            "left_deep_first_downs": 249,
            "left_deep_hit_as_threw": 251,
            "left_deep_interceptions": 252,
            "left_deep_passing_snaps": 253,
            "left_deep_penalties": None,
            "left_deep_sacks": 257,
            "left_deep_scrambles": 258,
            "left_deep_spikes": 259,
            "left_deep_thrown_aways": 260,
            "left_deep_touchdowns": 261,
            "left_deep_turnover_worthy_plays": 262,
            "left_deep_yards": 264,
            "left_deep_grade_pass": 250
        },
        "RIGHT": {
            "right_deep_aimed_passes": 396,
            "right_deep_attempts": 397,
            "right_deep_avg_depth_of_target": 399,
            "right_deep_bats": 401,
            "right_deep_big_time_throws": 402,
            "right_deep_completions": 405,
            "right_deep_dropbacks": 408,
            "right_deep_drops": 409,
            "right_deep_first_downs": 410,
            "right_deep_hit_as_threw": 412,
            "right_deep_interceptions": 413,
            "right_deep_passing_snaps": 414,
            "right_deep_penalties": None,
            "right_deep_sacks": 418,
            "right_deep_scrambles": 419,
            "right_deep_spikes": 420,
            "right_deep_thrown_aways": 421,
            "right_deep_touchdowns": 422,
            "right_deep_turnover_worthy_plays": 423,
            "right_deep_yards": 425,
            "right_deep_grade_pass": 411
        }
    },
    "INTERMEDIATE": {
        "CENTRAL": {
            "center_medium_aimed_passes": 105,
            "center_medium_attempts": 106,
            "center_medium_avg_depth_of_target": 108,
            "center_medium_bats": 110,
            "center_medium_big_time_throws": 111,
            "center_medium_completions": 114,
            "center_medium_dropbacks": 117,
            "center_medium_drops": 118,
            "center_medium_first_downs": 119,
            "center_medium_hit_as_threw": 121,
            "center_medium_interceptions": 122,
            "center_medium_passing_snaps": 123,
            "center_medium_penalties": None,
            "center_medium_sacks": 127,
            "center_medium_scrambles": 128,
            "center_medium_spikes": 129,
            "center_medium_thrown_aways": 130,
            "center_medium_touchdowns": 131,
            "center_medium_turnover_worthy_plays": 132,
            "center_medium_yards": 134,
            "center_medium_grade_pass": 120
        },
        "LEFT": {
            "left_medium_aimed_passes": 267,
            "left_medium_attempts": 268,
            "left_medium_avg_depth_of_target": 270,
            "left_medium_bats": 272,
            "left_medium_big_time_throws": 273,
            "left_medium_completions": 276,
            "left_medium_dropbacks": 279,
            "left_medium_drops": 280,
            "left_medium_first_downs": 281,
            "left_medium_hit_as_threw": 283,
            "left_medium_interceptions": 284,
            "left_medium_passing_snaps": 285,
            "left_medium_penalties": None,
            "left_medium_sacks": 289,
            "left_medium_scrambles": 290,
            "left_medium_spikes": 291,
            "left_medium_thrown_aways": 292,
            "left_medium_touchdowns": 293,
            "left_medium_turnover_worthy_plays": 294,
            "left_medium_yards": 296,
            "left_medium_grade_pass": 282
        },
        "RIGHT": {
            "right_medium_aimed_passes": 428,
            "right_medium_attempts": 429,
            "right_medium_avg_depth_of_target": 431,
            "right_medium_bats": 433,
            "right_medium_big_time_throws": 434,
            "right_medium_completions": 437,
            "right_medium_dropbacks": 440,
            "right_medium_drops": 441,
            "right_medium_first_downs": 442,
            "right_medium_hit_as_threw": 444,
            "right_medium_interceptions": 445,
            "right_medium_passing_snaps": 446,
            "right_medium_penalties": None,
            "right_medium_sacks": 450,
            "right_medium_scrambles": 451,
            "right_medium_spikes": 452,
            "right_medium_thrown_aways": 453,
            "right_medium_touchdowns": 454,
            "right_medium_turnover_worthy_plays": 455,
            "right_medium_yards": 457,
            "right_medium_grade_pass": 443
        }
    },
    "SHORT": {
        "CENTRAL": {
            "center_short_aimed_passes": 137,
            "center_short_attempts": 138,
            "center_short_avg_depth_of_target": 140,
            "center_short_bats": 142,
            "center_short_big_time_throws": 143,
            "center_short_completions": 146,
            "center_short_dropbacks": 149,
            "center_short_drops": 150,
            "center_short_first_downs": 151,
            "center_short_hit_as_threw": 153,
            "center_short_interceptions": 154,
            "center_short_passing_snaps": 155,
            "center_short_penalties": None,
            "center_short_sacks": 159,
            "center_short_scrambles": 160,
            "center_short_spikes": 161,
            "center_short_thrown_aways": 162,
            "center_short_touchdowns": 163,
            "center_short_turnover_worthy_plays": 164,
            "center_short_yards": 166,
            "center_short_grade_pass": 152
        },
        "LEFT": {
            "left_short_aimed_passes": 299,
            "left_short_attempts": 300,
            "left_short_avg_depth_of_target": 302,
            "left_short_bats": 304,
            "left_short_big_time_throws": 305,
            "left_short_completions": 308,
            "left_short_dropbacks": 311,
            "left_short_drops": 312,
            "left_short_first_downs": 313,
            "left_short_hit_as_threw": 315,
            "left_short_interceptions": 316,
            "left_short_passing_snaps": 317,
            "left_short_penalties": None,
            "left_short_sacks": 321,
            "left_short_scrambles": 322,
            "left_short_spikes": 323,
            "left_short_thrown_aways": 324,
            "left_short_touchdowns": 325,
            "left_short_turnover_worthy_plays": 326,
            "left_short_yards": 328,
            "left_short_grade_pass": 314
        },
        "RIGHT": {
            "right_short_aimed_passes": 460,
            "right_short_attempts": 461,
            "right_short_avg_depth_of_target": 463,
            "right_short_bats": 465,
            "right_short_big_time_throws": 466,
            "right_short_completions": 469,
            "right_short_dropbacks": 472,
            "right_short_drops": 473,
            "right_short_first_downs": 474,
            "right_short_hit_as_threw": 476,
            "right_short_interceptions": 477,
            "right_short_passing_snaps": 478,
            "right_short_penalties": None,
            "right_short_sacks": 482,
            "right_short_scrambles": 483,
            "right_short_spikes": 484,
            "right_short_thrown_aways": 485,
            "right_short_touchdowns": 486,
            "right_short_turnover_worthy_plays": 487,
            "right_short_yards": 489,
            "right_short_grade_pass": 475
        }
    }
}



PASSING_PRESSURE = {
    "BLITZ": {
        "blitz_aimed_passes": 8,
        "blitz_attempts": 9,
        "blitz_avg_depth_of_target": 10,
        "blitz_bats": 12,
        "blitz_big_time_throws": 13,
        "blitz_completions": 16,
        "blitz_dropbacks": 19,
        "blitz_drops": 21,
        "blitz_first_downs": 22,
        "blitz_hit_as_threw": 24,
        "blitz_interceptions": 25,
        "blitz_passing_snaps": 26,
        "blitz_penalties": None,
        "blitz_sacks": 30,
        "blitz_scrambles": 31,
        "blitz_spikes": 32,
        "blitz_thrown_aways": 33,
        "blitz_touchdowns": 34,
        "blitz_turnover_worthy_plays": 35,
        "blitz_yards": 37,
        "blitz_grades_pass": 23,
    },
    "NO_BLITZ": {
        "no_blitz_aimed_passes": 46,
        "no_blitz_attempts": 47,
        "no_blitz_avg_depth_of_target": 48,
        "no_blitz_bats": 50,
        "no_blitz_big_time_throws": 51,
        "no_blitz_completions": 54,
        "no_blitz_dropbacks": 57,
        "no_blitz_drops": 59,
        "no_blitz_first_downs": 60,
        "no_blitz_hit_as_threw": 62,
        "no_blitz_interceptions": 63,
        "no_blitz_passing_snaps": 64,
        "no_blitz_penalties": None,
        "no_blitz_sacks": 68,
        "no_blitz_scrambles": 69,
        "no_blitz_spikes": 70,
        "no_blitz_thrown_aways": 71,
        "no_blitz_touchdowns": 72,
        "no_blitz_turnover_worthy_plays": 73,
        "no_blitz_yards": 75,
        "no_blitz_grades_pass": 61,
    },
    "NO_PRESSURE": {
        "no_pressure_aimed_passes": 78,
        "no_pressure_attempts": 79,
        "no_pressure_avg_depth_of_target": 80,
        "no_pressure_bats": 82,
        "no_pressure_big_time_throws": 83,
        "no_pressure_completions": 86,
        "no_pressure_dropbacks": 89,
        "no_pressure_drops": 91,
        "no_pressure_first_downs": 92,
        "no_pressure_hit_as_threw": 94,
        "no_pressure_interceptions": 95,
        "no_pressure_passing_snaps": 96,
        "no_pressure_penalties": None,
        "no_pressure_sacks": 100,
        "no_pressure_scrambles": 101,
        "no_pressure_spikes": 102,
        "no_pressure_thrown_aways": 103,
        "no_pressure_touchdowns": 104,
        "no_pressure_turnover_worthy_plays": 105,
        "no_pressure_yards": 107,
        "no_pressure_grades_pass": 93,
    },
    "PRESSURE": {
        "pressure_aimed_passes": 111,
        "pressure_attempts": 112,
        "pressure_avg_depth_of_target": 113,
        "pressure_bats": 115,
        "pressure_big_time_throws": 116,
        "pressure_completions": 119,
        "pressure_dropbacks": 122,
        "pressure_drops": 124,
        "pressure_first_downs": 125,
        "pressure_hit_as_threw": 127,
        "pressure_interceptions": 128,
        "pressure_passing_snaps": 129,
        "pressure_penalties": None,
        "pressure_sacks": 133,
        "pressure_scrambles": 134,
        "pressure_spikes": 135,
        "pressure_thrown_aways": 136,
        "pressure_touchdowns": 137,
        "pressure_turnover_worthy_plays": 138,
        "pressure_yards": 140,
        "pressure_grades_pass": 126,
    }
}



NCAA_PASSING_PRESSURE = {
    "BLITZ": {
        "blitz_aimed_passes": 8,
        "blitz_attempts": 9,
        "blitz_avg_depth_of_target": 10,
        "blitz_bats": 12,
        "blitz_big_time_throws": 13,
        "blitz_completions": 16,
        "blitz_dropbacks": 19,
        "blitz_drops": 21,
        "blitz_first_downs": 22,
        "blitz_hit_as_threw": 24,
        "blitz_interceptions": 25,
        "blitz_passing_snaps": 26,
        "blitz_penalties": None,
        "blitz_sacks": 30,
        "blitz_scrambles": 31,
        "blitz_spikes": 32,
        "blitz_thrown_aways": 33,
        "blitz_touchdowns": 34,
        "blitz_turnover_worthy_plays": 35,
        "blitz_yards": 37,
        "blitz_grades_pass": 23,
    },
    "NO_BLITZ": {
        "no_blitz_aimed_passes": 46,
        "no_blitz_attempts": 47,
        "no_blitz_avg_depth_of_target": 48,
        "no_blitz_bats": 50,
        "no_blitz_big_time_throws": 51,
        "no_blitz_completions": 54,
        "no_blitz_dropbacks": 57,
        "no_blitz_drops": 59,
        "no_blitz_first_downs": 60,
        "no_blitz_hit_as_threw": 62,
        "no_blitz_interceptions": 63,
        "no_blitz_passing_snaps": 64,
        "no_blitz_penalties": None,
        "no_blitz_sacks": 68,
        "no_blitz_scrambles": 69,
        "no_blitz_spikes": 70,
        "no_blitz_thrown_aways": 71,
        "no_blitz_touchdowns": 72,
        "no_blitz_turnover_worthy_plays": 73,
        "no_blitz_yards": 75,
        "no_blitz_grades_pass": 61,
    },
    "NO_PRESSURE": {
        "no_pressure_aimed_passes": 78,
        "no_pressure_attempts": 79,
        "no_pressure_avg_depth_of_target": 80,
        "no_pressure_bats": 82,
        "no_pressure_big_time_throws": 83,
        "no_pressure_completions": 86,
        "no_pressure_dropbacks": 89,
        "no_pressure_drops": 91,
        "no_pressure_first_downs": 92,
        "no_pressure_hit_as_threw": 94,
        "no_pressure_interceptions": 95,
        "no_pressure_passing_snaps": 96,
        "no_pressure_penalties": None,
        "no_pressure_sacks": 100,
        "no_pressure_scrambles": 101,
        "no_pressure_spikes": 102,
        "no_pressure_thrown_aways": 103,
        "no_pressure_touchdowns": 104,
        "no_pressure_turnover_worthy_plays": 105,
        "no_pressure_yards": 107,
        "no_pressure_grades_pass": 93,
    },
    "PRESSURE": {
        "pressure_aimed_passes": 111,
        "pressure_attempts": 112,
        "pressure_avg_depth_of_target": 113,
        "pressure_bats": 115,
        "pressure_big_time_throws": 116,
        "pressure_completions": 119,
        "pressure_dropbacks": 122,
        "pressure_drops": 124,
        "pressure_first_downs": 125,
        "pressure_hit_as_threw": 127,
        "pressure_interceptions": 128,
        "pressure_passing_snaps": 129,
        "pressure_penalties": None,
        "pressure_sacks": 133,
        "pressure_scrambles": 134,
        "pressure_spikes": 135,
        "pressure_thrown_aways": 136,
        "pressure_touchdowns": 137,
        "pressure_turnover_worthy_plays": 138,
        "pressure_yards": 140,
        "pressure_grades_pass": 126,
    }
}



RECEIVING = {
    "avoided_tackles": 7,
    "contested_receptions": 10,
    "contested_targets": 11,
    "drops": 14,
    "first_downs": 15,
    "fumbles": 17,
    "inline_snaps": 24,
    "interceptions": 25,
    "penalties": 30,
    "receptions": 31,
    "routes": 33,
    "slot_snaps": 35,
    "targets": 37,
    "touchdows": 38,
    "wide_snaps": 40,
    "yards": 41,
    "yards_after_catch": 42,
    "grades_hands_drop": 18,
    "grades_pass_route": 22,
}



RECEIVING_DEPTH = {
    "BEHIND_LOS": {
        "CENTER": {
            "center_behind_los_avoided_tackles": 37,
            "center_behind_los_contested_receptions": 40,
            "center_behind_los_contested_targets": 41,
            "center_behind_los_drops": 43,
            "center_behind_los_first_downs": 44,
            "center_behind_los_fumbles": 45,
            "center_behind_los_inline_snaps": None,
            "center_behind_los_interceptions": 48,
            "center_behind_los_penalties": None,
            "center_behind_los_receptions": 53,
            "center_behind_los_routes": 55,
            "center_behind_los_slot_snaps": None,
            "center_behind_los_targets": 57,
            "center_behind_los_touchdows": 59,
            "center_behind_los_wide_snaps": None,
            "center_behind_los_yards": 60,
            "center_behind_los_yards_after_catch": 61,
            "center_behind_los_grades_hands_drop": 46,
            "center_behind_los_grades_pass_route": 47,
        },
        "LEFT": {
            "left_behind_los_avoided_tackles": 184,
            "left_behind_los_contested_receptions": 187,
            "left_behind_los_contested_targets": 188,
            "left_behind_los_drops": 190,
            "left_behind_los_first_downs": 191,
            "left_behind_los_fumbles": 192,
            "left_behind_los_inline_snaps": None,
            "left_behind_los_interceptions": 195,
            "left_behind_los_penalties": None,
            "left_behind_los_receptions": 200,
            "left_behind_los_routes": 202,
            "left_behind_los_slot_snaps": None,
            "left_behind_los_targets": 204,
            "left_behind_los_touchdows": 206,
            "left_behind_los_wide_snaps": None,
            "left_behind_los_yards": 207,
            "left_behind_los_yards_after_catch": 208,
            "left_behind_los_grades_hands_drop": 193,
            "left_behind_los_grades_pass_route": 194,
        },
        "RIGHT": {
            "right_behind_los_avoided_tackles": 330,
            "right_behind_los_contested_receptions": 333,
            "right_behind_los_contested_targets": 334,
            "right_behind_los_drops": 336,
            "right_behind_los_first_downs": 337,
            "right_behind_los_fumbles": 338,
            "right_behind_los_inline_snaps": None,
            "right_behind_los_interceptions": 341,
            "right_behind_los_penalties": None,
            "right_behind_los_receptions": 346,
            "right_behind_los_routes": 348,
            "right_behind_los_slot_snaps": None,
            "right_behind_los_targets": 350,
            "right_behind_los_touchdows": 352,
            "right_behind_los_wide_snaps": None,
            "right_behind_los_yards": 353,
            "right_behind_los_yards_after_catch": 354,
            "right_behind_los_grades_hands_drop": 339,
            "right_behind_los_grades_pass_route": 340,
        }
    },
    "DEEP": {
        "CENTER": {
            "center_deep_avoided_tackles": 66,
            "center_deep_contested_receptions": 69,
            "center_deep_contested_targets": 70,
            "center_deep_drops": 72,
            "center_deep_first_downs": 73,
            "center_deep_fumbles": 74,
            "center_deep_inline_snaps": None,
            "center_deep_interceptions": 77,
            "center_deep_penalties": None,
            "center_deep_receptions": 82,
            "center_deep_routes": 84,
            "center_deep_slot_snaps": None,
            "center_deep_targets": 86,
            "center_deep_touchdows": 88,
            "center_deep_wide_snaps": None,
            "center_deep_yards": 89,
            "center_deep_yards_after_catch": 90,
            "center_deep_grades_hands_drop": 75,
            "center_deep_grades_pass_route": 76,
        },
        "LEFT": {
            "left_deep_avoided_tackles": 213,
            "left_deep_contested_receptions": 216,
            "left_deep_contested_targets": 217,
            "left_deep_drops": 219,
            "left_deep_first_downs": 220,
            "left_deep_fumbles": 221,
            "left_deep_inline_snaps": None,
            "left_deep_interceptions": 224,
            "left_deep_penalties": None,
            "left_deep_receptions": 229,
            "left_deep_routes": 231,
            "left_deep_slot_snaps": None,
            "left_deep_targets": 233,
            "left_deep_touchdows": 235,
            "left_deep_wide_snaps": None,
            "left_deep_yards": 236,
            "left_deep_yards_after_catch": 237,
            "left_deep_grades_hands_drop": 222,
            "left_deep_grades_pass_route": 223,
        },
        "RIGHT": {
            "right_deep_avoided_tackles": 361,
            "right_deep_contested_receptions": 364,
            "right_deep_contested_targets": 365,
            "right_deep_drops": 367,
            "right_deep_first_downs": 368,
            "right_deep_fumbles": 369,
            "right_deep_inline_snaps": None,
            "right_deep_interceptions": 370,
            "right_deep_penalties": None,
            "right_deep_receptions": 375,
            "right_deep_routes": 377,
            "right_deep_slot_snaps": None,
            "right_deep_targets": 379,
            "right_deep_touchdows": 381,
            "right_deep_wide_snaps": None,
            "right_deep_yards": 382,
            "right_deep_yards_after_catch": 383,
            "right_deep_grades_hands_drop": 358,
            "right_deep_grades_pass_route": 359,
        }
    },
    "INTERMEDIATE": {
        "CENTER": {
            "center_medium_avoided_tackles": 95,
            "center_medium_contested_receptions": 98,
            "center_medium_contested_targets": 99,
            "center_medium_drops": 101,
            "center_medium_first_downs": 102,
            "center_medium_fumbles": 103,
            "center_medium_inline_snaps": None,
            "center_medium_interceptions": 106,
            "center_medium_penalties": None,
            "center_medium_receptions": 111,
            "center_medium_routes": 113,
            "center_medium_slot_snaps": None,
            "center_medium_targets": 115,
            "center_medium_touchdows": 117,
            "center_medium_wide_snaps": None,
            "center_medium_yards": 118,
            "center_medium_yards_after_catch": 119,
            "center_medium_grades_hands_drop": 104,
            "center_medium_grades_pass_route": 105,
        },
        "LEFT": {
            "left_medium_avoided_tackles": 242,
            "left_medium_contested_receptions": 245,
            "left_medium_contested_targets": 246,
            "left_medium_drops": 248,
            "left_medium_first_downs": 249,
            "left_medium_fumbles": 250,
            "left_medium_inline_snaps": None,
            "left_medium_interceptions": 253,
            "left_medium_penalties": None,
            "left_medium_receptions": 258,
            "left_medium_routes": 260,
            "left_medium_slot_snaps": None,
            "left_medium_targets": 262,
            "left_medium_touchdows": 264,
            "left_medium_wide_snaps": None,
            "left_medium_yards": 265,
            "left_medium_yards_after_catch": 266,
            "left_medium_grades_hands_drop": 251,
            "left_medium_grades_pass_route": 252,
        },
        "RIGHT": {
            "right_medium_avoided_tackles": 388,
            "right_medium_contested_receptions": 391,
            "right_medium_contested_targets": 392,
            "right_medium_drops": 394,
            "right_medium_first_downs": 395,
            "right_medium_fumbles": 396,
            "right_medium_inline_snaps": None,
            "right_medium_interceptions": 399,
            "right_medium_penalties": None,
            "right_medium_receptions": 404,
            "right_medium_routes": 406,
            "right_medium_slot_snaps": None,
            "right_medium_targets": 408,
            "right_medium_touchdows": 410,
            "right_medium_wide_snaps": None,
            "right_medium_yards": 411,
            "right_medium_yards_after_catch": 412,
            "right_medium_grades_hands_drop": 397,
            "right_medium_grades_pass_route": 398,
        }
    },
    "SHORT": {
        "CENTER": {
            "center_short_avoided_tackles": 124,
            "center_short_contested_receptions": 127,
            "center_short_contested_targets": 128,
            "center_short_drops": 130,
            "center_short_first_downs": 131,
            "center_short_fumbles": 132,
            "center_short_inline_snaps": None,
            "center_short_interceptions": 135,
            "center_short_penalties": None,
            "center_short_receptions": 140,
            "center_short_routes": 142,
            "center_short_slot_snaps": None,
            "center_short_targets": 144,
            "center_short_touchdows": 146,
            "center_short_wide_snaps": None,
            "center_short_yards": 147,
            "center_short_yards_after_catch": 148,
            "center_short_grades_hands_drop": 133,
            "center_short_grades_pass_route": 134,
        },
        "LEFT": {
            "left_short_avoided_tackles": 271,
            "left_short_contested_receptions": 274,
            "left_short_contested_targets": 275,
            "left_short_drops": 277,
            "left_short_first_downs": 278,
            "left_short_fumbles": 279,
            "left_short_inline_snaps": None,
            "left_short_interceptions": 282,
            "left_short_penalties": None,
            "left_short_receptions": 287,
            "left_short_routes": 289,
            "left_short_slot_snaps": None,
            "left_short_targets": 291,
            "left_short_touchdows": 293,
            "left_short_wide_snaps": None,
            "left_short_yards": 294,
            "left_short_yards_after_catch": 295,
            "left_short_grades_hands_drop": 280,
            "left_short_grades_pass_route": 281,
        },
        "RIGHT": {
            "right_short_avoided_tackles": 417,
            "right_short_contested_receptions": 420,
            "right_short_contested_targets": 421,
            "right_short_drops": 423,
            "right_short_first_downs": 424,
            "right_short_fumbles": 425,
            "right_short_inline_snaps": None,
            "right_short_interceptions": 428,
            "right_short_penalties": None,
            "right_short_receptions": 433,
            "right_short_routes": 435,
            "right_short_slot_snaps": None,
            "right_short_targets": 437,
            "right_short_touchdows": 439,
            "right_short_wide_snaps": None,
            "right_short_yards": 440,
            "right_short_yards_after_catch": 441,
            "right_short_grades_hands_drop": 426,
            "right_short_grades_pass_route": 427,
        }
    }
}



RECEIVING_SCHEME = {
    "MAN": {
        "man_avoided_tackles": 10,
        "man_contested_receptions": 13,
        "man_contested_targets": 14,
        "man_drops": 16,
        "man_first_downs": 17,
        "man_fumbles": 18,
        "man_inline_snaps": None,
        "man_interceptions": 21,
        "man_penalties": None,
        "man_receptions": 26,
        "man_routes": 28,
        "man_slot_snaps": None,
        "man_targets": 30,
        "man_touchdows": 32,
        "man_wide_snaps": None,
        "man_yards": 33,
        "man_yards_after_catch": 34,
        "man_grades_hands_drop": 19,
        "man_grades_pass_route": 20,
    },
    "ZONE": {
        "zone_avoided_tackles": 40,
        "zone_contested_receptions": 43,
        "zone_contested_targets": 44,
        "zone_drops": 46,
        "zone_first_downs": 47,
        "zone_fumbles": 48,
        "zone_inline_snaps": None,
        "zone_interceptions": 51,
        "zone_penalties": None,
        "zone_receptions": 56,
        "zone_routes": 58,
        "zone_slot_snaps": None,
        "zone_targets": 60,
        "zone_touchdows": 62,
        "zone_wide_snaps": None,
        "zone_yards": 63,
        "zone_yards_after_catch": 64,
        "zone_grades_hands_drop": 49,
        "zone_grades_pass_route": 50,
    }
}



RUSHING = {
    "attempts": 6,
    "avoided_tackles": 7,
    "brekaway_attempts": 8,
    "breakaway_yards": 10,
    "designed_yards": 12,
    "explosive": 18,
    "first_downs": 19,
    "fumbles": 21,
    "gap_attempts": 22,
    "penalties": 32,
    "run_plays": 36,
    "scramble_yards": 37,
    "scrambles": 38,
    "touchdowns": 41,
    "yards": 42,
    "yards_after_contact": 43,
    "zone_attempts": 47,
    "grades_run": 29,
    "grades_hands_fumble": 23
}



BLOCKING = {
    "grades_pass_block": 10,
    "grades_run_block": 11,
    "penalties": 18,
    "snap_counts_ce": 22,
    "snap_counts_lg": 23,
    "snap_counts_lt": 24,
    "snap_counts_offense": 25,
    "snap_counts_pass_block": 26,
    "snap_counts_pass_play": 27,
    "snap_counts_rg": 28,
    "snap_counts_rt": 29,
    "snap_counts_run_block": 30,
    "snap_counts_te": 31
}



PASS_BLOCKING = {
    "grades_pass_block": 8,
    "hits_allowed": 9,
    "hurries_allowed": 10,
    "pressures_allowed": 16,
    "sacks_allowed": 17,
    "snap_counts_pass_play": 19,
    "true_pass_set_grades_pass_block": 20,
    "true_pass_set_hits_allowed": 21,
    "true_pass_set_hurries_allowed": 22, 
    "true_pass_set_pressures_allowed": 27,
    "true_pass_set_sacks_allowed": 28, 
    "true_pass_set_snap_counts_pass_play": 30
}



RUN_BLOCKING = {
    "gap_grades_run_block": 8,
    "gap_snap_counts_run_block": 10,
    "grades_run_block": 13,
    "snap_counts_run_block": 16,
    "penalties": 14,
    "zone_grades_run_block": 18,
    "zone_snap_counts_run_block": 20
}



PASS_RUSH = {
    "batted_passes": 6,
    "grades_pass_rush_defense": 7,
    "hits": 10,
    "hurries": 11,
    "pass_rush_opp": 12,
    "pass_rush_wins": 15,
    "penalties": 16,
    "sacks": 18,
    "snap_counts_pass_play": 19,
    "snap_counts_pass_rush": 20,
    "total_pressures": 21,
    "true_pass_set_batted_passes": 22,
    "true_pass_set_grades_pass_rush_defense": 23,
    "true_pass_set_hits": 24,
    "true_pass_set_hurries": 25,
    "true_pass_set_pass_rush_opp": 26,
    "true_pass_set_pass_rush_wins": 29,
    "true_pass_set_sacks": 31,
    "true_pass_set_snap_counts_pass_play": 32,
    "true_pass_set_snap_counts_pass_rush": 33,
    "true_pass_set_total_pressures": 34
}



RUN_DEFENCE = {
    "assists": 6,
    "avg_depth_of_tackle": 7,
    "forced_fumbles": 9,
    "grades_run_defense": 15,
    "grades_tackle": 16,
    "missed_tackles": 18,
    "penalties": 19,
    "run_stop_opp": 20,
    "stops": 23, 
    "tackles": 24
}



COVERAGE = {
    "avg_depth_of_target": 7,
    "dropped_ints": 13,
    "forced_incompletes": 14,
    "grades_coverage_defense": 17,
    "interceptions": 23,
    "pass_break_ups": 27,
    "receptions": 30,
    "snap_counts_coverage": 31,
    "targets": 35,
    "touchdowns": 36,
    "yards": 37,
    "yards_after_catch": 38
}



COVERAGE_SCHEME = {
    "MAN": {
        "avg_depth_of_target": 10,
        "dropped_ints": 15,
        "forced_incompletes": 16,
        "grades_coverage_defense": 18,
        "interceptions": 19,
        "pass_break_ups": 23,
        "receptions": 25,
        "snap_counts_coverage": 26,
        "targets": 31,
        "touchdowns": 32,
        "yards": 33,
        "yards_after_catch": 34
    },
    "ZONE": {
        "avg_depth_of_target": 39,
        "dropped_ints": 44,
        "forced_incompletes": 45,
        "grades_coverage_defense": 47,
        "interceptions": 48,
        "pass_break_ups": 52,
        "receptions": 54,
        "snap_counts_coverage": 55,
        "targets": 60,
        "touchdowns": 61,
        "yards": 62,
        "yards_after_catch": 63
    }
}